In [1]:
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [2]:
sc_data = pd.read_html('https://xn--swqwdp22azlcvue.biz/all_rank.php')

In [11]:
sc_data[0].head()

   大学平均偏差値     大学名         地域      順位 ランク
0     70.0  日本医科大学  神奈川県(東京都)  1/754位   S
1     69.3  国際教養大学        秋田県  2/754位   S
2     69.0    一橋大学        東京都  3/754位   S
3     68.8    東京大学        東京都  4/754位   S
4     66.9  慶應義塾大学  神奈川県(東京都)  5/754位   S

In [12]:
sc_data[1].head()

,0,1
0,(adsbygoogle=window.adsbygoogle||[]).push({});,(adsbygoogle=window.adsbygoogle||[]).push({});

In [13]:
sc_data[2].head()

   大学平均偏差値     大学名    地域        順位 ランク
0     54.1    専修大学  神奈川県  101/754位   B
1     54.1  大阪教育大学   大阪府  101/754位   B
2     54.0  金沢医科大学   石川県  103/754位   C
3     54.0  明治薬科大学   東京都  103/754位   C
4     54.0  東京芸術大学   東京都  103/754位   C

In [16]:
for i in range(len(sc_data)):
    print(sc_data[i].head())

   大学平均偏差値     大学名         地域      順位 ランク
0     70.0  日本医科大学  神奈川県(東京都)  1/754位   S
1     69.3  国際教養大学        秋田県  2/754位   S
2     69.0    一橋大学        東京都  3/754位   S
3     68.8    東京大学        東京都  4/754位   S
4     66.9  慶應義塾大学  神奈川県(東京都)  5/754位   S
                                                0  \
0  (adsbygoogle=window.adsbygoogle||[]).push({});

                                                1
0  (adsbygoogle=window.adsbygoogle||[]).push({});
   大学平均偏差値     大学名    地域        順位 ランク
0     54.1    専修大学  神奈川県  101/754位   B
1     54.1  大阪教育大学   大阪府  101/754位   B
2     54.0  金沢医科大学   石川県  103/754位   C
3     54.0  明治薬科大学   東京都  103/754位   C
4     54.0  東京芸術大学   東京都  103/754位   C
                                                0  \
0  (adsbygoogle=window.adsbygoogle||[]).push({});

                                                1
0  (adsbygoogle=window.adsbygoogle||[]).push({});
   大学平均偏差値     大学名    地域        順位 ランク
0     50.5    畿央大学   奈良県  201/754位   C
1     50.5  東京都市大学  神奈川県  201/754位   C
2     50.5  県立広島大学   広島県  201/754位   C
3     50.5    佐賀大学   佐賀県  201/754位   C
4     50.4   武蔵野大学   東京都  205/754位   C
                                                0  \
0  (adsbygoogle=window.adsbygoogle||[]).push({});

                                                1
0  (adsbygoogle=window.adsbygoogle||[]).push({});
   大学平均偏差値     大学名    地域        順位 ランク
0     46.5    東海大学  神奈川県  300/754位   D
1     46.5  宮崎公立大学   宮崎県  300/754位   D
2     46.4    玉川大学   東京都  303/754位   D
3     46.4    松山大学   愛媛県  303/754位   D
4     46.3  中村学園大学   福岡県  305/754位   D
                                                0  \
0  (adsbygoogle=window.adsbygoogle||[]).push({});

                                                1
0  (adsbygoogle=window.adsbygoogle||[]).push({});
   大学平均偏差値       大学名   地域        順位 ランク
0     41.8    大阪芸術大学  大阪府  401/754位   E
1     41.7   清泉女学院大学  長野県  402/754位   E
2     41.7  大阪電気通信大学  大阪府  402/754位   E
3     41.6    神戸常盤大学  兵庫県  404/754位   E
4     41.6    大阪産業大学  大阪府  404/754位   E
                                                0  \
0  (adsbygoogle=window.adsbygoogle||[]).push({});

                                                1
0  (adsbygoogle=window.adsbygoogle||[]).push({});

In [32]:
rank_data = pd.concat([sc_data[0],sc_data[2],sc_data[4],sc_data[6],sc_data[8]])

In [34]:
rank_data.reset_index(drop=True)

     大学平均偏差値         大学名         地域        順位 ランク
0       70.0      日本医科大学  神奈川県(東京都)    1/754位   S
1       69.3      国際教養大学        秋田県    2/754位   S
2       69.0        一橋大学        東京都    3/754位   S
3       68.8        東京大学        東京都    4/754位   S
4       66.9      慶應義塾大学  神奈川県(東京都)    5/754位   S
5       66.6       早稲田大学        埼玉県    6/754位   S
6       66.1      東京工業大学        東京都    7/754位   S
7       65.9        京都大学        京都府    8/754位   S
8       65.0     国際基督教大学        東京都    9/754位   S
9       65.0   東京慈恵会医科大学        東京都    9/754位   S
10      65.0      兵庫医科大学        兵庫県    9/754位   S
11      64.5        上智大学        東京都   12/754位   S
12      64.4     東京外国語大学        東京都   13/754位   S
13      63.0  聖マリアンナ医科大学       神奈川県   14/754位   A
14      63.0      川崎医科大学        岡山県   14/754位   A
15      63.0      大阪医科大学        大阪府   14/754位   A
16      62.3      関西医科大学        大阪府   17/754位   A
17      61.9        明治大学        東京都   18/754位   A
18      61.7      青山学院大学       神奈川県   19/754位   A
19      61.6        大阪大学        大阪府   20/754位   A
20      61.3        立教大学        埼玉県   21/754位   A
21      61.1    お茶の水女子大学        東京都   22/754位   A
22      61.1        神戸大学        兵庫県   22/754位   A
23      61.1    東京医科歯科大学   千葉県(東京都)   22/754位   A
24      61.0      豊田工業大学        愛知県   25/754位   A
25      60.9    神戸市外国語大学        兵庫県   26/754位   A
26      60.8       同志社大学        京都府   27/754位   A
27      60.8        東北大学        宮城県   27/754位   A
28      60.5      横浜国立大学       神奈川県   29/754位   A
29      60.5    京都府立医科大学        京都府   29/754位   A
..       ...         ...        ...       ...  ..
724     34.7  長崎ウエスレヤン大学        長崎県  724/754位   F
725     34.7      東北女子大学        青森県  724/754位   F
726     34.6        別府大学        大分県  727/754位   F
727     34.5     愛知みずほ大学        愛知県  728/754位   F
728     34.5        育英大学        群馬県  728/754位   F
729     34.5      九州情報大学        福岡県  728/754位   F
730     34.5      郡山女子大学        福島県  728/754位   F
731     34.5       高野山大学       和歌山県  728/754位   F
732     34.5      杉野服飾大学        東京都  728/754位   F
733     34.5      大阪音楽大学        大阪府  728/754位   F
734     34.5    稚内北星学園大学        北海道  728/754位   F
735     34.5        東亜大学        山口県  728/754位   F
736     34.5    東北公益文科大学        山形県  728/754位   F
737     34.5        徳山大学        山口県  728/754位   F
738     34.5      日本経済大学        東京都  728/754位   F
739     34.5      福島学院大学        福島県  728/754位   F
740     34.5     北海道情報大学        北海道  728/754位   F
741     34.4      作新学院大学        栃木県  742/754位   F
742     34.4      四国学院大学        香川県  742/754位   F
743     34.4        松蔭大学       神奈川県  742/754位   F
744     34.4       南九州大学        宮崎県  742/754位   F
745     34.3      岐阜女子大学        岐阜県  746/754位   F
746     34.3      中京学院大学        岐阜県  746/754位   F
747     34.3      中国学園大学        岡山県  746/754位   F
748     34.0        芦屋大学        兵庫県  749/754位   G
749     34.0      岡山学院大学        岡山県  749/754位   G
750     34.0      山梨英和大学        山梨県  749/754位   G
751     34.0       身延山大学        山梨県  749/754位   G
752     34.0      長岡崇徳大学        新潟県  749/754位   G
753     34.0        富士大学        岩手県  749/754位   G

[754 rows x 5 columns]

In [33]:
rank_data

     大学平均偏差値         大学名         地域        順位 ランク
0       70.0      日本医科大学  神奈川県(東京都)    1/754位   S
1       69.3      国際教養大学        秋田県    2/754位   S
2       69.0        一橋大学        東京都    3/754位   S
3       68.8        東京大学        東京都    4/754位   S
4       66.9      慶應義塾大学  神奈川県(東京都)    5/754位   S
5       66.6       早稲田大学        埼玉県    6/754位   S
6       66.1      東京工業大学        東京都    7/754位   S
7       65.9        京都大学        京都府    8/754位   S
8       65.0     国際基督教大学        東京都    9/754位   S
9       65.0   東京慈恵会医科大学        東京都    9/754位   S
10      65.0      兵庫医科大学        兵庫県    9/754位   S
11      64.5        上智大学        東京都   12/754位   S
12      64.4     東京外国語大学        東京都   13/754位   S
13      63.0  聖マリアンナ医科大学       神奈川県   14/754位   A
14      63.0      川崎医科大学        岡山県   14/754位   A
15      63.0      大阪医科大学        大阪府   14/754位   A
16      62.3      関西医科大学        大阪府   17/754位   A
17      61.9        明治大学        東京都   18/754位   A
18      61.7      青山学院大学       神奈川県   19/754位   A
19      61.6        大阪大学        大阪府   20/754位   A
20      61.3        立教大学        埼玉県   21/754位   A
21      61.1    お茶の水女子大学        東京都   22/754位   A
22      61.1        神戸大学        兵庫県   22/754位   A
23      61.1    東京医科歯科大学   千葉県(東京都)   22/754位   A
24      61.0      豊田工業大学        愛知県   25/754位   A
25      60.9    神戸市外国語大学        兵庫県   26/754位   A
26      60.8       同志社大学        京都府   27/754位   A
27      60.8        東北大学        宮城県   27/754位   A
28      60.5      横浜国立大学       神奈川県   29/754位   A
29      60.5    京都府立医科大学        京都府   29/754位   A
..       ...         ...        ...       ...  ..
324     34.7  長崎ウエスレヤン大学        長崎県  724/754位   F
325     34.7      東北女子大学        青森県  724/754位   F
326     34.6        別府大学        大分県  727/754位   F
327     34.5     愛知みずほ大学        愛知県  728/754位   F
328     34.5        育英大学        群馬県  728/754位   F
329     34.5      九州情報大学        福岡県  728/754位   F
330     34.5      郡山女子大学        福島県  728/754位   F
331     34.5       高野山大学       和歌山県  728/754位   F
332     34.5      杉野服飾大学        東京都  728/754位   F
333     34.5      大阪音楽大学        大阪府  728/754位   F
334     34.5    稚内北星学園大学        北海道  728/754位   F
335     34.5        東亜大学        山口県  728/754位   F
336     34.5    東北公益文科大学        山形県  728/754位   F
337     34.5        徳山大学        山口県  728/754位   F
338     34.5      日本経済大学        東京都  728/754位   F
339     34.5      福島学院大学        福島県  728/754位   F
340     34.5     北海道情報大学        北海道  728/754位   F
341     34.4      作新学院大学        栃木県  742/754位   F
342     34.4      四国学院大学        香川県  742/754位   F
343     34.4        松蔭大学       神奈川県  742/754位   F
344     34.4       南九州大学        宮崎県  742/754位   F
345     34.3      岐阜女子大学        岐阜県  746/754位   F
346     34.3      中京学院大学        岐阜県  746/754位   F
347     34.3      中国学園大学        岡山県  746/754位   F
348     34.0        芦屋大学        兵庫県  749/754位   G
349     34.0      岡山学院大学        岡山県  749/754位   G
350     34.0      山梨英和大学        山梨県  749/754位   G
351     34.0       身延山大学        山梨県  749/754位   G
352     34.0      長岡崇徳大学        新潟県  749/754位   G
353     34.0        富士大学        岩手県  749/754位   G

[754 rows x 5 columns]

In [35]:
rank_data.to_csv('大学偏差値データ.csv')